# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/A/Desktop/EDA234/CONSTRAINS.xdc

# IP: ip/printf/printf.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==printf || ORIG_REF_NAME==printf} -quiet] -quiet
